[package]
name = "nix-melt"
version = "0.1.2"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "A ranger-like flake.lock viewer"
readme = "README.md"
homepage = "https://github.com/nix-community/nix-melt"
repository = "https://github.com/nix-community/nix-melt"
license = "MPL-2.0"
keywords = ["cli", "flake", "nix", "tui", "viewer"]
categories = ["command-line-utilities"]

[dependencies]
color-eyre = "0.6.2"
crossterm = "0.26.1"
eyre = "0.6.8"
indexmap = { version = "1.9.3", features = ["serde"] }
parse-display = "0.8.0"
rustc-hash = "1.1.0"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "2.3.3"
thiserror = "1.0.40"

[dependencies.clap]
version = "4.2.4"
features = ["cargo", "derive", "unicode", "wrap_help"]

[dependencies.ratatui]
version = "0.20.1"
default-features = false
features = ["crossterm"]

[dependencies.time]
version = "0.3.20"
features = ["formatting", "local-offset", "serde"]

[build-dependencies]
clap = { version = "4.2.4", features = ["derive"] }
clap_complete = "4.2.1"
clap_mangen = "0.2.10"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
